version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.8
    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: Build
          command: |
            sudo pip install -r requirements.txt
            mkdir /tmp/artifacts
            pyinstaller --onefile mergepdf.py
            cp /tmp/dist/mergepdf* /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts
