version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.8
    steps:
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
            mkdir /tmp/artifacts
            pyinstaller --onefile mergepdf.py
            cp dist/mergepdf.* /tmp/artifacts
            
          name: Test
      - store_artifacts:
          path: /tmp/artifacts
