version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.8
    working_directory: ~/mydir
    steps:
      - checkout
      - run:
          name: Build
          command: |
            sudo pip install -r requirements.txt
            mkdir /tmp/artifacts
            pyinstaller --onefile mergepdf.py
            cp ~/mydir/dist/mergepdf /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=0.1
            echo ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/artifacts
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/artifacts
            
