version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.8
    steps:
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
            pyinstaller --onefile mergepdf.py
          name: Test
